### ISSUE TITLE
Paranoid circos error

### ISSUE THREAD

**Issue by pdiakumis** [umccr/umccrise#111]
Randomly happens on both ICA and HPC, on multiple samples, not reproducibly, gets resolved after deleting circos colour cache file and restarting on HPC at least. Worth noting it only happens with the `circos_baf` rule. Need to figure out a different way to generate those it seems. Not high priority right now, but still annoying - 3 cases so far.

```
at /miniconda/envs/umccrise_hmf/bin/../lib/Circos/Error.pm line 425, <F> line 888.
	Circos::Error::fatal_error("warning", "paranoid") called at /miniconda/envs/umccrise_hmf/bin/../lib/Circos/Debug.pm line 396
	Circos::Debug::printwarning("Problem reading color cache file /tmp/circos.colorlist.trn.d3"...) called at /miniconda/envs/umccrise_hmf/bin/../lib/Circos/Colors.pm line 209
	Circos::Colors::allocate_colors(GD::Image=SCALAR(0x562bceb63e88)) called at /miniconda/envs/umccrise_hmf/bin/../lib/Circos.pm line 692
	Circos::run("Circos", "outputfile", "SBJ00987__MDX210224.circos_baf.png", "_cwd", "/scratch/working_dir/L2101016__L2101015", "outputdir", "work/SBJ00987__MDX210224/purple/circos_baf", "svg", ...) called at /miniconda/envs/umccrise_hmf/bin/circos line 536
```

- SBJ02057 ([slack](https://umccr.slack.com/archives/C8CG6K76W/p1649727538680279))
- SBJ02235 ([slack](https://umccr.slack.com/archives/C025TLC7D/p1657168129325579?thread_ts=1657153966.016119&cid=C025TLC7D))
- SBJ00987 ([slack](https://umccr.slack.com/archives/C8CG6K76W/p1657773964632429))
- SBJ02091 ([slack](https://umccr.slack.com/archives/C8CG6K76W/p1695755328313159))

**Comment by pdiakumis** [comment]
Closing since we haven't hit this in over a year.

**Comment by pdiakumis** [comment]
We just hit this coincidentally with a re-run of SBJ02091, added to the list above.

**Comment by pdiakumis** [comment]
And we got another one (`umccr__cohort__umccrise__SBJ00743__L2100265__20231014ff91314a`).

**Comment by pdiakumis** [comment]
I think we can actually add the `-noparanoid` option to the circos plot making:

```
-paranoid -noparanoid Make all warnings fatal or not (default: paranoid).
```

**Comment by hongwingl** [comment]
FYI, this error occurs because circos writes the color lists to a file in the tmp directory. When multiple circos runs at the same time, they could overwrite this file and cause issues. We are working on a fix.

This failure is a little difficult to reproduce, we might put in a speculative fix into purple by overriding the `TMPDIR` environment variable of CIRCOS
