### ISSUE TITLE
Improve Pierian input preparation

### ISSUE THREAD

**Issue by pdiakumis** [umccr/umccrise#112]
Currently we prepare SNV, SV, and CNV inputs for Pierian using the steps in <https://github.com/umccr/umccrise/blob/f92f319db0cad61646b4f9a868eb07608fa816a5/umccrise/somatic.smk#L314>

In summary:

- SNVs: subset final PASSed set to only tumor sample
- SVs: copy final prioritised Manta set
- CNVs: copy final PURPLE CNVs (after renaming CN column)

i.e., we don't do anything special.

Pierian though has the following restrictions:

- SNVs: requires the number of variants to be < 50,000
- SVs and CNVs: not sure (@mhlunimelb please enlighten me!)

In hypermutated cases we are currently subsetting these sets manually based on a BED file, but it would be good to automate this.

**Comment by ohofmann** [comment]
I was absolutely sure we create a VCF limited to 50k variants somewhere in umccrise already (post PCGR). Since that's not the case I would prefilter against PierianDX's RefSeq BED file for any sample with more than 50k SNV variants. I am not aware of any limits to CN and SVs - or at least we've not hit that limit yet.

**Comment by pdiakumis** [comment]
That one was for SVs where we dynamically remove by tier until we get < 50K - https://github.com/umccr/umccrise/blob/f92f319db0cad61646b4f9a868eb07608fa816a5/umccrise/structural.smk#L166

**Comment by pdiakumis** [comment]
Resolved via #113

**Comment by pdiakumis** [comment]
After testing more samples it's become apparent that we need to constrict the regions a bit more.

**Comment by pdiakumis** [comment]
Example filtering approach for SBJ02686 (based on the changes in #116):

```
Preparing Pierian SNV subset (if required)
Total: 260998
Total in gene regions: 148461
dump NONCODING, intergenic_variant: 128658
dump NONCODING, intergenic_variant or intron_variant: 55399
dump NONCODING, intergenic_variant or intron_variant or intron_variant|_non_coding_transcript_variant: 11438
Verdict:
 do not include noncoding intergenic/intronic/_non_coding_transcript_variant
Command:
 bcftools view -R hg38_refseq_gencode_all_genes_v1.bed.gz SBJ02686__PRJ221972-somatic-PASS.vcf.gz | bcftools filter -e "(PCGR_TIER == 'NONCODING') && (PCGR_CONSEQUENCE == 'intergenic_variant' || PCGR_CONSEQUENCE == 'intron_variant' || PCGR_CONSEQUENCE == 'intron_variant|_non_coding_transcript_variant')"
 ```
