### ISSUE TITLE
Update ClinVar db

### ISSUE THREAD

**Issue by pdiakumis** [umccr/umccrise#122]
I've got a germline variant which has come through CPSR in one of my cases as non-ClinVar, although it does have a ClinVar entry (<https://www.ncbi.nlm.nih.gov/clinvar/variation/1334551/?new_evidence=true>). Annotations in ClinVar are from 2021 onwards for this variant. I notice under the CPSR documentation the version of ClinVar is from 2020. In fact all the annotation resources listed are pre-2021. Would this be the reason? Is it possible to update any of these resources in CPSR?

[Slack Message](https://umccr.slack.com/archives/C025TLC7D/p1666245385409609)

**Comment by ohofmann** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [umccrise release: Testing GH](https://trello.com/c/w0ieaqQM/1346-umccrise-release-testing-gh)

**Comment by pdiakumis** [comment]
PCGR refdata has been updated since this, closing.
