### ISSUE TITLE
Add versioneer and Docker versioning

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#13]
Basically apply https://github.com/warner/python-versioneer and perhaps more importantly DockerHub/Dockerfile versioning to be able to discern which releases might be problematic in dev/production.

**Comment by vladsaveliev** [comment]
Pushed a versioned image: https://hub.docker.com/r/umccr/umccrise/tags/

Should we get rid of latest now?

**Comment by brainstorm** [comment]
Awesome, yeah, thanks! :D

**Comment by reisingerf** [comment]
With regards to versioning of docker images, [umccr/test-vault-secrets-injection](https://github.com/umccr/test-vault-secrets-injection) could be a solution.

**Comment by vladsaveliev** [comment]
I got this in my working branch:
https://github.com/umccr/umccrise/blob/multiqc/.travis.yml#L55-L66

Any reason it might not work? Versions images, and skips for the -dev versions pretty nicely.

**Comment by vladsaveliev** [comment]
Pushed that logic to master now

**Comment by brainstorm** [comment]
Thanks, reason for that was that versions 0.8 and 0.8.1 were overwritten twice (at least). Just wanted to make sure that stable versioning was in place, thanks!

**Comment by reisingerf** [comment]
Who is updating the Version.txt file?

**Comment by vladsaveliev** [comment]
Will try the approach with tagging and will remove VERSION.txt, thank Florian for tons of good points!

Not gonna use the vault magic for now, but will experiment with it at some point.

**Comment by vladsaveliev** [comment]
That's implemented in the new release. Also versioneer looked too complex for me, so I made https://github.com/vladsaveliev/versionpy. 

Unfortunately Travis times out building the Docker image, so gotta be pushing new versions to Dockerhub manually until I switch to CircleCI.
