### ISSUE TITLE
HRD: include DRAGEN hrdscore.csv results

### ISSUE THREAD

**Issue by pdiakumis** [umccr/umccrise#148]
File `hrdscore.csv` is included under DRAGEN 4.2.4 outputs. Structure is:

```
Sample,LOH_Score,TAI_Score,LST_Score,HRD_Score
FOO,9,30,20,59
```

**Comment by ohofmann** [comment]
Help me out with this one. I'd like to see this in the CancerReporter - does this now move to an issue in https://github.com/umccr/gpgr ?

**Comment by pdiakumis** [comment]
Yep, or wherever @scwatts would like to track these.

**Comment by scwatts** [comment]
Definitely in umccr/gpgr!
