### ISSUE TITLE
Add checks for missing/empty files

### ISSUE THREAD

**Issue by pdiakumis** [umccr/umccrise#4]
* Need to catch empty `af_tumor.txt` and `af_tumor_az300.txt` files.
    * Results in `Error: Faceting variables must have at least one value`. 
* Need to catch if `lof` column is empty (`NA`s) in `sv-prioritize-manta-pass.tsv`, or else just shows an empty table.
* Need to also make sure `suppressors.txt` and `signatures_probabilities.txt` files exist.

**Comment by pdiakumis** [comment]
Not sure if this is handled in any other way now but putting this down just in case (I'm using same strategy in rock):

https://stackoverflow.com/a/19919198/2169986

If it's handled, please close Vlad ;-)

**Comment by vladsaveliev** [comment]
Catching `af_tumor.txt` and `af_tumor_az300.txt` in snakefiles, as well as verifying the reference gene lists exist.

Any reason `sv-prioritize-manta-pass.tsv` would miss the lof column?
