### ISSUE TITLE
Cancer report error in mutational_sigs_prep chunk

### ISSUE THREAD

**Issue by pdiakumis** [umccr/umccrise#43]
Just logging it here.

* Version: `umccrise_017_2020_Jan_dev` on Gadi.
* Using DRAGEN input.

```
label: mutational_sigs_prep
Quitting from lines 203-264 (cancer_report.Rmd)
Error: All columns in a tibble must be 1d or 2d objects:
* Column `Signature` is NULL
<error/rlang_error>
All columns in a tibble must be 1d or 2d objects:
* Column `Signature` is NULL
Backtrace:

  1. ├─rmarkdown::render(...)
  2. │ └─knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
  3. │   └─knitr:::process_file(text, output)
  4. │     ├─base::withCallingHandlers(...)
  5. │     ├─knitr:::process_group(group)
  6. │     └─knitr:::process_group.block(group)
  7. │       └─knitr:::call_block(x)
  8. │         └─knitr:::block_exec(params)
  9. │           ├─knitr:::in_dir(...)
 10. │           └─knitr:::evaluate(...)
 11. │             └─evaluate::evaluate(...)
 12. │               └─evaluate:::evaluate_call(...)
 13. │                 ├─evaluate:::timing_fn(...)
 14. │                 ├─base:::handle(...)
 15. │                 ├─base::withCallingHandlers(...)
 16. │
```

**Comment by pdiakumis** [comment]
It’s partly to do with that there’s only one SNV in that dataset, and partly that it just finds one signature. The current subsetting drops the row name since it's a single element, so you end up with a plain numeric instead of a named numeric which throws an error.

I've fixed that in https://github.com/umccr/umccrise/pull/44. Hopefully.

**Comment by ohofmann** [comment]
Nice find. Could we add some logic to not calculate signatures if we have less than ~500 variants?

**Comment by pdiakumis** [comment]
I was planning to parameterise the `eval`uation of most chunks in the report based on the availability/nrow of files, so yes, on the todo.
