### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by lbeltrame** [umccr/umccrise#47]
I understand this set of tools is mainly for use with UMCCR, but I've seen several things of interest I'd like to put in my own workflows (or even adapt this workflow to my institution). However, there is no license provided in the repository, which means not even redistribution is technically possible (modulo the exceptions given in GIthub's Terms of Service).

So I can't even look at the code at this point.

**Comment by ohofmann** [comment]
Ooops. Assume MIT license - didn't realize we hadn't added this yet. @vladsaveliev , chime up if you disagree please.

**Comment by vladsaveliev** [comment]
Thank you Luca! My bad. I just added the MIT license now. Turns out I was forgot about it in many of my repos.
