### ISSUE TITLE
Add a link to an example report with synthetic / validation data in the README

### ISSUE THREAD

**Issue by lbeltrame** [umccr/umccrise#48]
In the "nice to have" category: it would be good to have a look at how a report looks like (using validation / synthetic datasets)

**Comment by ohofmann** [comment]
Yep, that's on the todo list (and already there for the internal repo / docs).

**Comment by ohofmann** [comment]
@vladsaveliev just added examples for the SEQC-II reference cell line to [the docs folder](https://github.com/umccr/umccrise/tree/master/docs).

**Comment by vladsaveliev** [comment]
Added example the reports also now as hosted static HTMLs so one doesn't need to download them to view in a browser, and added clickable screenshots into [README](https://github.com/umccr/umccrise)

Thanks so much Luka for the idea! I really overlooked it.

Vlad
