### ISSUE TITLE
Missed bcbio qc metrics

### ISSUE THREAD

**Issue by ohofmann** [umccr/umccrise#60]
@vladsaveliev Low priority, but can you point me at the code that moves bcbio's qc metrics for the _batch_ to umccrise's multiqc input?

E.g., `2021-01-11T2249_All_WGS_SBJ00662/final/2021-01-13_2021-01-11T2249_All_WGS_SBJ00662-merged/multiqc/report/metrics` ends up in `umccrised/work/SBJ00662__SBJ00662_MDX200243_L2100010/multiqc_data/2021-01-13_2021-01-11T2249_All_WGS_SBJ00662-merged/multiqc/report/metrics` but I can't seem to find where that copy happens.

**Comment by vladsaveliev** [comment]
Hi Oliver :)

We are not moving that folder. We are rerunning MultiQC instead, using both bcbio QC files and umccrise QC files combined as input. That combining is happening in [this rule](https://github.com/umccr/umccrise/blob/master/umccrise/multiqc.smk#L67), and the following MultiQC run is happening [down here](https://github.com/umccr/umccrise/blob/master/umccrise/multiqc.smk#L189). As a result a _new_ folder named `multiqc_data ` is generated.

**Comment by ohofmann** [comment]
Happy New Year here as well ;-) Okay, I'll take another look - trying to create a reproducible example why the bcbio metrics are being missed for a recent sample. More soon!

**Comment by ohofmann** [comment]
Still not sure I am getting this. Looking at https://github.com/umccr/umccrise/blob/d84f843cdfa27f237fc9740bfa31b811154f8ba0/umccrise/multiqc.smk#L31 makes it _sound_ like you are copying bcbio qc metrics over to umccrise's work directory?

**Comment by vladsaveliev** [comment]
`find_bcbio_qc_files` finds input files for the MultiQC run. MultiQC takes a list of QC files as input. Those that are generated by other tools (bcftools, samtools, verifybamid, - whatever MultiQC supports). We combine the QC files generated by tools within bcbio and umccrise workflows, and put the paths to them into one big list, which we write to a txt file. That list is fed into the `multiqc` command with the `-l` flag. 
This is where that list is written to a file: https://github.com/umccr/umccrise/blob/d84f843cdfa27f237fc9740bfa31b811154f8ba0/umccrise/multiqc/prep_data.py#L65-L70
This is where it's used: https://github.com/umccr/umccrise/blob/d84f843cdfa27f237fc9740bfa31b811154f8ba0/umccrise/multiqc.smk#L191

The folder `multiqc/report/metrics`, on the other hand, is auto-generated by MultiQC, so we don't touch it manually.

**Comment by ohofmann** [comment]
Okay, I need to step through that code one by one I think. I _thought_ you re-run MultiQC based on the `filelist.txt` generated in `umccrised/work/SBJ00648__SBJ00648_MDX200237_L2100008/multiqc_data`. _That_ contains pointers to

```
work/SBJ00648__SBJ00648_MDX200237_L2100008/multiqc_data/2021-01-13_2021-01-11T2249_All_WGS_SBJ00648-merged/multiqc/report/metrics/target_info.yaml
work/SBJ00648__SBJ00648_MDX200237_L2100008/multiqc_data/2021-01-13_2021-01-11T2249_All_WGS_SBJ00648-merged/multiqc/report/metrics/SBJ00648_MDX200237_L2100008_bcbio.txt
work/SBJ00648__SBJ00648_MDX200237_L2100008/multiqc_data/2021-01-13_2021-01-11T2249_All_WGS_SBJ00648-merged/multiqc/report/metrics/SBJ00648_MDX200236_L2100007_bcbio.txt
```

I.e., copies of bcbio's metrics files. But you are saying those are MultiQC's output, not input. I'll try to recreate this in smaller steps - thanks for the pointers :)

**Comment by vladsaveliev** [comment]
Ah, I understand what are you are referring to bcbio metrics: those `*_bcbio.txt` files. I forgot that they are copied into `report/metrics` in bcbio. So they are not generated by MultiQC indeed. Umccrise should be picking `SBJ00648_MDX200237_L2100008_bcbio.txt` as one of the input files for its own MultiQC run.

**Comment by ohofmann** [comment]
Phew, at least I got that right. I've narrowed it down to `batch.find_qc_files` which seems to be missing them in rare edge cases. Almost there :)

**Comment by ohofmann** [comment]
Alright, got it. Traced it all the way back to bcbio which has files in the MultiQC filelist (`/multiqc/list_files_final.txt`) with the wrong path information. Don't ask me why that happened, I'll take that to the bcbio repo. Thanks for the pointers!

**Comment by vladsaveliev** [comment]
Huh. So sorry you had to dig into that.

**Comment by ohofmann** [comment]
No, no, it's fun - just a bit time poor.
