### ISSUE TITLE
Fix vcf2maf warnings

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#61]
https://github.com/mskcc/vcf2maf/issues/181#issuecomment-729937258

They are filling up cloudwatch/logs unnecessarily and difficult troubleshooting:

```
% cat 000000 | grep -v "Use of uninitialized value in list assignment at /miniconda/envs/umccrise/bin/vcf2maf.pl" > readable-umccrise-fail.log

% ls -alh readable-umccrise-fail.log 000000
-rw-rw-rw- 1 rvalls staff 3.8M Apr  8 14:21 000000
-rw-r--r-- 1 rvalls staff 278K Apr  8 14:24 readable-umccrise-fail.log
```

**Comment by pdiakumis** [comment]
That seems to be coming from https://github.com/umccr/umccrise/blob/da898304b1aa7e96bbf5b3584fcd558867ea4c93/umccrise/somatic.smk#L265
I'm not even sure if we use the output MAF file anywhere..
I'll filter out those warnings.

**Comment by skanwal** [comment]
MAF files are used in a couple research projects. Vlad had added these to umccrise to save us time generating these outside post-processing step.

For reference https://umccr.slack.com/archives/C8CG6K76W/p1594349080042500?thread_ts=1594348509.040800&cid=C8CG6K76W

**Comment by pdiakumis** [comment]
Oh thanks @skanwal! Yeah, I'll just `grep -v` those warnings.
