### ISSUE TITLE
Fix AWS documentation

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#62]
The current README.md points to a deprecated Terraform stack. UMCCRISE now uses CDK instead.

Whereas the HPC side is well documented, the AWS side needs a bit more attention. Namely the following but a bit better explained ;) :

https://github.com/umccr/infrastructure/tree/master/cdk/apps/umccrise

Essentially you need an EC2 instance that can run docker containers. Then use/follow the umccrise Batch script to pull in the data and run the actual umccrise command:

https://github.com/umccr/infrastructure/blob/master/cdk/apps/umccrise/assets/umccrise-wrapper.sh

In principle you should be able to kick off the exact same Batch job, log into the instance (need to check if SSM is available) and just pause the umccrise process (which should keep the Batch job running).

**Comment by pdiakumis** [comment]
Closing since we're transitioning to ICA.
I promise to add more docs to whatever we end up with!
