### ISSUE TITLE
Ship derived tool logs to CloudWatch instead of the local instance

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#64]
Tool workflow logs such as purple:

```
2021-04-04T02:16:09.024Z     log: log/purple/SBJ00703__SBJ00703_PRJ210147_L2100196_rerun/SBJ00703__SBJ00703_PRJ210147_L2100196_rerun.purple.log
```

When running on an AWS environment should be shipped to a CloudWatch LogGroup, i.e:

https://gist.github.com/olegdulin/fd18906343d75142a487b9a9da9042e0

Otherwise those are gone whenever the Batch instance finishes or dies. It not only facilitates troubleshooting but actionable provenance since those logs can be analyzed for defects/patterns/etc.. with AWS services and managed tooling.

Perhaps even snakemake allows some logging handler mechanism to facilitate this sub-workflow `stdout/stderr` log shipping.

**Comment by pdiakumis** [comment]
Closing since we're transitioning to ICA.
