### ISSUE TITLE
Compress multiqc_data.json

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#65]
For consistency with the rest of the reports generated (which are all `.gz`):

https://github.com/umccr/data-portal-apis/pull/201/files#diff-b44efe9a184a94acff47483f52c87e58310be7f6ffb68bf9eb93c0296123fc47R202

**Comment by pdiakumis** [comment]
Closing since we're transitioning to ICA.
Will keep ^ in mind when we get to that point.

**Comment by brainstorm** [comment]
This particular issue does not have to do that much with AWS vs ICA, or am I missing sth? :-S

**Comment by pdiakumis** [comment]
It doesn't have anything to do with umccrise either (which is getting frozen), it's down to the future post-processor (i.e. all the table/json exporting will happen there, wherever that is).
