### ISSUE TITLE
GDrive PCGR download step in README.md

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#7]
Reading on your README.md for PCGR installation/steps:

```
# Download the data bundle
gdrive download 1tOyPmzgXkSZjPJQOojFQxUP8JlQuQqLq  # hg19
gdrive download 1cKq-rgSNCYPCUJ38pCi_xy6_PJH-FZWD  # hg38
gunzip -c pcgr.databundle.grch37.20180422.tgz | tar xvf -
gunzip -c pcgr.databundle.grch37.20180422.tgz | tar xvf -
bash pcgr/install_no_docker/install.sh
```

From where did you install that `gdrive` tool?
Does it require authentication?
Do you **manually** download the tarballs on each release?
How do you plan to automate that?

Did you have a look at the way I did it (and why) on my ansible role to perform that task without authentication and automatically?:

https://github.com/umccr/pcgr-deploy/blob/master/ansible/roles/databundle/tasks/main.yml

**Comment by vladsaveliev** [comment]
`gdrive` is available for download here https://github.com/prasmussen/gdrive or homebrew

It's just another way to download reference bundles from here https://github.com/sigven/pcgr. I guess same as your `gdown.pl`

`gdrive` requires authentication, that's why I can only download it manually and I don't know how to automate it. Did you solve that problem with `gdown.pl`?

**Comment by brainstorm** [comment]
Yes, that is the whole point of using a smelly perl script, it bypasses authentication, allowing for automation.

**Comment by vladsaveliev** [comment]
`gdown.pl` is a fantastic tool, I can't believe I missed it. Thanks for the tip. Will point Sigve to it, will be useful for other PCGR users to have it in README

**Comment by brainstorm** [comment]
The command that you specify in the readme does not seem to work for me :-S

I used this one instead now (check URL closely: `view`vs `uc`):

`./gdown.pl https://drive.google.com/uc?id=1cKq-rgSNCYPCUJ38pCi_xy6_PJH-FZWD pcgr.databundle.grch37.tgz`

**Comment by brainstorm** [comment]
Oh, disregard that, you are actually using a newer `gdown.pl` version that fixes that url issue, awesome, thanks! :D

**Comment by brainstorm** [comment]
https://github.com/wkentaro/gdown ;)
