### ISSUE TITLE
Standard python testsuite

### ISSUE THREAD

**Issue by brainstorm** [umccr/umccrise#8]
IMHO, testing this software should be easier than creating a "loader script" (manually copy pasted from your README), then exporting an environment variable and finally running nosetests.

Could you create a `tests` subdirectory like any other python project:

http://docs.python-guide.org/en/latest/writing/structure/

That pulls/prepares/automates the testing? In essence following the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) principle? ;)

**Comment by vladsaveliev** [comment]
Sorry it's not like any other python project. A lot of things can be designed to be easier, but it's not obviously rational to polish a pipeline that is only used by one person at the moment.

Will make the dir and make tests automatically pull the data, that's a good suggestion.

However loading the environment can't be avoided, I think.

**Comment by brainstorm** [comment]
Sorry you have to go through the struggle of polishing your software and having it more accessible to others in the lab and elsewhere, but it's actually used by more than one person now and probably (hopefully) many more ;)

**Comment by vladsaveliev** [comment]
Since now simply `nosetests tests` works, closing
